import arr from './array';
import bool from './boolean';
import date from './date';
import func from './function';
import nul from './null';
import num from './number';
import obj from './object';
import prom from './promise';
import reg from './regexp';
import str from './string';
import und from './undefined';
import like from './like';
import objEmp from "./object_empty";
import same from "./same";
declare const _default: {
    arr: typeof arr;
    bool: typeof bool;
    date: typeof date;
    func: typeof func;
    nul: typeof nul;
    num: typeof num;
    obj: typeof obj;
    prom: typeof prom;
    reg: typeof reg;
    str: typeof str;
    und: typeof und;
    like: typeof like;
    objEmp: typeof objEmp;
    same: typeof same;
};
export default _default;
//# sourceMappingURL=index.d.ts.map